// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using cdpTracker_Api.Data;

#nullable disable

namespace cdpTracker_Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260418194254_RenameWorkersToKiosks")]
    partial class RenameWorkersToKiosks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("cdpTracker_Api.Models.Envelope", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WorkerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("WorkerId");

                    b.ToTable("Envelopes");
                });

            modelBuilder.Entity("cdpTracker_Api.Models.Worker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Kiosko")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Workers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Kiosko = 0,
                            Name = "Kiosko 2",
                            PasswordHash = "kiosko2",
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            Kiosko = 1,
                            Name = "Kiosko 3",
                            PasswordHash = "kiosko3",
                            Role = 0
                        },
                        new
                        {
                            Id = 3,
                            Kiosko = 2,
                            Name = "Kiosko 5",
                            PasswordHash = "kiosko5",
                            Role = 0
                        });
                });

            modelBuilder.Entity("cdpTracker_Api.Models.Envelope", b =>
                {
                    b.HasOne("cdpTracker_Api.Models.Worker", "Worker")
                        .WithMany("Envelopes")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("cdpTracker_Api.Models.Worker", b =>
                {
                    b.Navigation("Envelopes");
                });
#pragma warning restore 612, 618
        }
    }
}
